// MEAL LIST
export const FETCH_MEAL_LIST = 'FETCH_MEAL_LIST';
export const CLEAR_MEAL_LIST = 'CLEAR_MEAL_LIST';

// MEAL
export const FETCH_MEAL_INFO = 'FETCH_MEAL_INFO';
export const CLEAR_MEAL_INFO = 'CLEAR_MEAL_INFO';

// DETAILS
export const FETCH_DETAILS = 'FETCH_DETAILS';

// AREAS
export const FETCH_AREAS = 'FETCH_AREAS';

// INGREDIENTS
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';

// APP STATE
export const UPDATE_CATEGORIES_LOADED = 'UPDATE_CATEGORIES_LOADED';
export const UPDATE_MEAL_LIST_LOADED = 'UPDATE_MEAL_LIST_LOADED';
export const UPDATE_AREAS_LOADED = 'UPDATE_AREAS_LOADED';
export const UPDATE_INGREDIENTS_LOADED = 'PDATE_INGREDIENTS_LOADED';

// CATEGORIES
export const FETCH_CATEGORY_NAMES = 'FETCH_CATEGORY_NAMES';
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const DEFAULT = 'DEFAULT';
